project:
  type: book
  output-dir: _book
  execute-dir: project
  
editor: source

book:
  title: "fm-unix"
  author: "Martin Frigaard"
  description: |
    A Unix/Linux Field Manual
  search: true
  #site-url: https://mjfrigaard.github.io/fm-unix/
  #repo-url: https://github.com/mjfrigaard/fm-unix
  #repo-branch: main
  #repo-actions: [edit, issue]
  chapters:
    - index.qmd 
    - preface.qmd
    - intro.qmd
    - part: setups.qmd
      chapters:
        - sh_term.qmd
        - vms.qmd
        - quarto.qmd
    - part: basics.qmd
      chapters:
        - dirs.qmd
        - files.qmd
        - sys.qmd
        - vars.qmd
    - part: syntax.qmd
      chapters:
        - commands.qmd
        - arguments.qmd
        - options.qmd
        - pipes.qmd
    - part: text.qmd
      chapters:
        - symbols_patterns.qmd
        - text_commands.qmd
        - text_editors.qmd
    - part: scripts.qmd
      chapters:
        - format.qmd
        - permissions.qmd
    - part: use_cases.qmd
      chapters:
        - file_size.qmd
  appendices:
        - syntax_ref.qmd
        - glossary.qmd
        - macos.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: arrow
    code-block-bg: "#eff0ef"
    code-block-border-left: "#696969"
    code-overflow: scroll
    number-sections: false
    callout-appearance: simple 
    callout-icon: false
    code-link: false
    code-annotations: hover
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    dpi: 320
    df-print: kable
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.055em
    linestretch: 1.25
    fig-width: 7
    fig-height: 5
    engine: knitr

execute:
  freeze: true
