project:
  type: book
  output-dir: _book
  execute-dir: project
  
editor:
  render-on-save: true

book:
  title: "FM-Linux"
  author: "Martin Frigaard"
  description: |
    A Linux Field Manual
  search: true
  site-url: https://mjfrigaard.github.io/fm-linux/
  repo-url: https://github.com/mjfrigaard/fm-linux
  #repo-branch: main
  #repo-actions: [edit, issue]
  chapters:
    - index.qmd 
    - preface.qmd
    - p1.qmd
    - part: setups.qmd
      chapters:
        - vms.qmd
        - wsl.qmd
        - shells.qmd
        - terminals.qmd
    - part: basics.qmd
      chapters:
        - dirs.qmd
        - files.qmd
        - sys.qmd
        - usr_grp.qmd
        - permissions.qmd
    - part: syntax.qmd
      chapters:
        - commands.qmd
        - arguments.qmd
        - options.qmd
        - pipes.qmd
        - vars.qmd
    - p2.qmd
    - part: text.qmd
      chapters:
        - wildcards.qmd
        - special_chars.qmd
        - regex.qmd
        - text_commands.qmd
    - part: txt_edit.qmd
      chapters:
        - vim.qmd
        - nano.qmd
        - emacs.qmd
    - part: scripts.qmd
      chapters:
        - format.qmd
    - p3.qmd
    - part: nw_fund.qmd
      chapters:
        - nw_configs.qmd
        - nw_dns.qmd
        - nw_ip_routing.qmd
    - part: nw_firewall_secure.qmd
      chapters:
        - nw_monitor_troubleshoot.qmd
        - nw_vpns_encrypt.qmd
        - nw_virtual_containers.qmd
    - p4.qmd
    - part: maintenance.qmd
      chapters:
        - installs.qmd
    - part: performance.qmd
      chapters:
        - file_size.qmd
  appendices:
        - syntax_ref.qmd
        - data.qmd
        - fish.qmd
        - macos.qmd
        - quarto.qmd
        - glossary.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: arrow
    date: last-modified
    date-format: iso
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#02577A"
    code-overflow: scroll
    number-sections: false
    callout-appearance: minimal
    callout-icon: false
    code-link: false
    code-annotations: hover
    dpi: 320
    df-print: kable
    fig-format: retina
    #fig-asp: 0.618
    fontsize: 1.055em
    linestretch: 1.35
    fig-width: 7
    fig-height: 5
    engine: knitr
    mermaid:
      theme: default

execute:
  freeze: true
