project:
  type: book
  output-dir: _book
  execute-dir: project
  
editor: source

book:
  title: "fm-unix"
  author: "Martin Frigaard"
  description: |
    A Unix Field Manual
  search: true
  #site-url: https://mjfrigaard.github.io/fm-unix/
  #repo-url: https://github.com/mjfrigaard/fm-unix
  #repo-branch: main
  #repo-actions: [edit, issue]
  chapters:
    - index.qmd 
    - part: intro.qmd
      chapters:
        - setup.qmd
        - syntax.qmd
        - files_folders.qmd
        - text.qmd
        - pipes.qmd
    - part: scripts.qmd
      chapters:
        - format.qmd
        - permissions.qmd
  appendices:
        - glossary.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: radical
    code-block-bg: "#1E2229"
    code-block-border-left: "#A5FFE1"
    number-sections: false
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    dpi: 320
    df-print: kable
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.025em
    linestretch: 1.15
    fig-width: 7
    fig-height: 5
    engine: knitr

execute:
  freeze: true


