project:
  type: book
  output-dir: _book
  
editor: source

book:
  title: "fm-unix"
  author: "Martin Frigaard"
  description: |
    A Unix Field Manual
  search: true
  #site-url: https://mjfrigaard.github.io/fm-unix/
  #repo-url: https://github.com/mjfrigaard/fm-unix
  #repo-branch: main
  #repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - preface.qmd
    - part: intro.qmd
      chapters:
        - setup.qmd
        - common_commands.qmd
        - advanced_commands.qmd
        - pipes.qmd
    - part: scripts.qmd
      chapters:
        - format.qmd
        - permissions.qmd
  appendices:
        - references.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    highlight-style: radical
    code-block-bg: "#262626"
    code-block-border-left: "#73FA91"
    number-sections: false
    toc: true
    toc-depth: 4
    toc-expand: true
    toc-title: Contents
    toc-location: right
    embed-resources: true
    dpi: 320
    df-print: kable
    fig-format: retina
    fig-asp: 0.618
    fontsize: 1.025em
    linestretch: 1.15
    fig-width: 7
    fig-height: 5
    engine: knitr

# knitr:
#   opts_chunk: 
#     collapse: true
#     comment: "## "
#     message: false
#     warning: false

# execute: 
#   eval: true
#   freeze: true
#   echo: true


